version: '${DockerVersion}'
services:
  rabbitmq:
    container_name: rabbitmq
    restart: on-failure
    image: rabbitmq:3.12.3-management-alpine
    ports:
      - "${RabbitMQServer_OutPORT}:${RabbitMQServerPort}"
      - "${RabbitMQManagement_OutPORT}:${RabbitMQManagementPort}"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  csharp_api:
    container_name: csharp
    restart: on-failure
    #image: ${CSharp_API_Image}
    build:
      context: ./API/API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

    volumes:
      - csharp:/src
    ports:
    - "8080:80"
    - "8081:443"
    depends_on:
      - rabbitmq
  
  # ImageAPI:
  #   container_name: Images_API
  #   #image: ${Images_API_Image}
  #   build:
  #     context: ./ImagesAPI
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${Images_API_OutPORT}:${Images_API_InPORT}"
  #   volumes:
  #     - ImageAPI:/app

  # PdfAPI:
  #   container_name: pdfapi
  #   #image: ${Pdf_API_Image}
  #   build:
  #     context: ./pdf-service
  #     dockerfile: Dockerfile
  #   volumes:
  #     - pdfapi:/app
  #   depends_on:
  #     - API

volumes:
  csharp:
 #ImageAPI:
  pdfapi:
  rabbitmq:

  